# The list of worlds this feature is enabled in
enabled-worlds:
  - world
  - world_nether
  - world_the_end

# Should the plugin require the player to have the permission to keep their inventory?
# If false everyone will keep inventory
permission: true