name: Build
on:
  push:
    branches: [ master ]
    paths:
      - "paper/**"
      - "sponge/**"
      - "common/**"
      - "build.gradle.kts"
      - "gradle.properties"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with gradle
        run: ./gradlew clean shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            paper/build/libs/BetterKeepInventory-paper-*.jar
            sponge/build/libs/BetterKeepInventory-sponge-*.jar