# NOTE: DO NOT HAVE THE KEEP INVENTORY GAMERULE ENABLED WITH THIS PLUGIN

# Global default settings that affect all worlds. Set all of them to false for vanilla functionality (No keep inventory)

# "keep" refers to what should be kept when the player dies which is not configurable

# Should the permission "betterkeepinventory.keep" be required for a player to "keep" on death
# If false everyone will "keep"
require-permission: false
# Should the player "keep" when killed by another player. This uses a combat tracker so it counts even if it is not a "direct" player kill
# e.g. If a player falls or burns to death while in combat this will classify as a player death. Uses Minecrafts built in tracker
keep-on-player-death: false
# Should the player "keep" on a natural death. Fall damage, starving, drowning etc
keep-on-natural-death: true
# Should the player "keep" when killed by a mob
keep-on-mob-death: true
# Should the player "keep" if they commited suicide. With arrows, end crystal etc
keep-on-suicide: false

# "keep" settings

# When the player dies should their inventory be kept
keep-inventory-items-on-death: true
# When the player dies should their EXP level be kept.
# The higher level you are the more EXP needed to level up so dying with 10 levels and 50% keep EXP will not respawn the player with 5 levels
# The value can also be a number from 0 to 1, with 1 meaning that all EXP is kept and 0 is none
# 0.5 - Keeps only half the EXP
keep-exp-on-death: 1.0

# World specific settings. These will override the above global settings for the specified world
worlds:
  # The name of the world
  world:
    # Should these settings override the global ones. Set to false to disable the override
    enabled: false
    require-permission: false
    keep-on-killed-by-player: false
    keep-on-natural-death: true
    keep-on-mob-death: true
    keep-inventory-items-on-death: true
    keep-exp-on-death: 0.5
  world_nether:
    enabled: false
    require-permission: true
    keep-on-killed-by-player: false
    keep-inventory-items-on-death: true
    keep-exp-on-death: 1.0
    # The "keep-on-natural-death" and "keep-on-mob-death" options have been left out. These two will default to the global
    # defaults set at the top of the file while the other settings that are specified will have whatever option is set
    # above inside the world section