name: ${name}
version: ${version}
main: ${group}.paper.${name}Paper
api-version: 1.21
authors: [ JustDoom ]
website: https://imjustdoom.com
softdepend:
  - BetterReload
permissions:
  betterkeepinventory.commands:
    default: op
    description: Command for plugin
    children:
      betterkeepinventory.reload: true
  betterkeepinventory.keep:
    default: false
    description: Keep inventory on death